### ISSUE TITLE
Create a metric from GDAC holdings measuring number of long time series.

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#1]
Long time series are the main product of the OceanSITES community.  Currently long time series are collected in the [DATA_GRIDDED](http://dods.ndbc.noaa.gov/thredds/catalog/oceansites/DATA_GRIDDED/catalog.html) directory of the THREDDS servers.  

The goal is to work with PIs to create scientifically valid, long term time series that result from combining multiple individual deployments into a single product.

Meghan, and Bob from the steering committee will be involved in scoping out this project. Diane and Jen from NOAA/COD are interested in pursuing and publishing these metrics.

**Comment by tcarval** [comment]
Duplicates a previous action.
