### ISSUE TITLE
Register OceanSITES metadata in B2FIND

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#18]
Thierry

**Comment by tcarval** [comment]
We should proceed step by step.
1. Get a DOI for OceanSITES GDAC data
2. Provide the DOI to B2FIND (EU EUDAT cloud infrastructure catalogue).
EUDAT : the collaborative Pan-European infrastructure for research

That is what we did for Argo.
Argo GDAC DOI: http://doi.org/10.17882/42182
This DOI is provided by Seanoe, a data publisher: http://www.seanoe.org/
EUDAT harvests Seanoe catalogue, and displays Argo DOI on its catalogue B2FIND
https://eudat.eu/services/b2find
http://b2find.eudat.eu/dataset/2e62c7c5-5f40-534f-8a75-b97a3b4d71e6

**Comment by hmsnaith** [comment]
As per discussions at AtlantOS, some providers already have DOIs for their data through other routes - so a single DOI for OceanSITES GDAC holdings might not be the best option

**Comment by tcarval** [comment]
Not important issue.
