### ISSUE TITLE
Document WMO ID - PLATFORM link in Metadata spreadsheet

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#22]
Champika

Edit the JCOMMOPS public metadata to include OceanSITES-WMO ID link as documented in OceanSITES catalog spreadsheet.  This link is necessary to track real time distribution on the GTS via [OSMC](http://www.osmc.noaa.gov).  Search for "OceanSITES" on the main monitoring screen.

**Comment by hmsnaith** [comment]
Any movement on this?
As others probably have, I have a script (Matlab) to set the wmo code for moorings I (or Maureen) have some responsibility for. Would it be useful to put that code in to software repository?

**Comment by hmsnaith** [comment]
i think this should now be addressed through the new JCOMMOPS metadata site.
However, it's not clear to me where the codes are populated from.
These should be linked to a vocab server than will confirm correct codes are used, or recognise when a new code is required

**Comment by tcarval** [comment]
The metadata spreadsheet is no more used.
