### ISSUE TITLE
Update links on oceansites.org/data and dods.ndbc.noaa.gov/oceansites.

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#3]
There are four URLs that we should be pointing people toward to access data.  While we might change this UI in the future, for now we should be consistent with listing data access locations uniformly.

Currently [oceansites.org/data](oceansites.org/data) lists the Ifremer FTP server and the NDBC THREDDS server.  Please include all five links below on oceansites.org/data.

[NDBC OceanSITES Web Page](http://dods.ndbc.noaa.gov/oceansites): http://dods.ndbc.noaa.gov/oceansites
[NDBC FTP](ftp://data.ndbc.noaa.gov/data/oceansites/): ftp://data.ndbc.noaa.gov/data/oceansites/
[NDBC THREDDS Catalog](http://dods.ndbc.noaa.gov/thredds/catalog/oceansites/catalog.html): http://dods.ndbc.noaa.gov/thredds/catalog/oceansites/catalog.html

[Ifremer FTP](ftp://ftp.ifremer.fr/ifremer/oceansites/): ftp://ftp.ifremer.fr/ifremer/oceansites/
[Ifremer THREDDS Catalog](http://tds0.ifremer.fr/thredds/CORIOLIS-OCEANSITES-GDAC-OBS/CORIOLIS-OCEANSITES-GDAC-OBS.html): http://tds0.ifremer.fr/thredds/CORIOLIS-OCEANSITES-GDAC-OBS/CORIOLIS-OCEANSITES-GDAC-OBS.html 

Also, the NDBC web page should be updated to at least include links to both the NDBC THREDDS and FTP servers (currently only links to the THREDDS server can be found).  Ideally the NDBC web site would also point to the two relevant Ifremer sites.

**Comment by dpsnowden** [comment]
@tcarval is there an equivalent page at Ifremer to the NDBC info page?  Something that is for humans to view and learn about the OceanSITES GDAC at IFremer?  If so, please post here.  

Also, could you add the ERDDAP endpoint to this issue so that we can update web pages accordingly.

**Comment by cgallage** [comment]
Five links are added to the OceanSITES webpage @ http://www.oceansites.org/data/index.html
on 18/07/2016

**Comment by tcarval** [comment]
Answer to @dpsnowden : there is no equivalent at Ifremer of the NDBC info page. There is no strong reason to have one, the "master" OceanSITES web site is http://www.oceansites.org/

**Comment by dpsnowden** [comment]
OK, @cgallage and @tcarval feel free to close issues when you complete them.  

We will  create a separate issue to update the web site with the ERDDAP links when they are available.
