### ISSUE TITLE
Create human readable symbolic links to the DATA and DATA_GRIDDED directories.

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#30]
Create soft links; do not actually move files.  Jing/Thierry to discuss details.

The general problem that the steering team asked us to deal with is that the DATA and DATA_GRIDDED are not easily understandable.

**Comment by tcarval** [comment]
I just created the following soft links on Ifremer GDAC:
DATA                                    ->           deployment_data
DATA_GRIDDED               ->            long_timeseries

Can you confirm that this is what we want ?
ftp://ftp.ifremer.fr/ifremer/oceansites/

**Comment by dpsnowden** [comment]
@jing-at-ndbc can you confirm this is the desired result?  Will this propagate to THREDDS also?  

@ngalbraith is this your understanding of the goal?

**Comment by ngalbraith** [comment]
Yes, this looks right to me, after prowling a bit and seeing that deployment_data and long_timeseries contain the same files as DATA and GRIDDED_DATA, respectively. 

It's not obvious, looking at the ftp site in a web browser, that the new 'directories' are directories - but I don't suppose many people come in that route, via a browser to that URL.

What I expected to see (where symbolic links are indented) was: 
Data 
    deployment_data
Data_gridded 
   long_timeseries
but obviously the order of the items depends on how the browser is sorting the list in the particular web session.

Thanks!

**Comment by dpsnowden** [comment]
Before closing we need to confirm that the change has also been made at NDBC and that we understand what to do to make the change visible on THREDDS (and ERDDAP if necessary).

**Comment by jing-at-ndbc** [comment]
Agree with Nan on her comments. I have added the soft links to NDBC THREDDS server and two FTP servers.

**Comment by dpsnowden** [comment]
Closing per @ngalbraith review.  @jing-at-ndbc or @tcarval pleae feel free to close issues assigned to you that are complete.  If you generate a pull request in order to complete your task, have some else merge the code/documentation changes based on their review.
