### ISSUE TITLE
Create a repository for code sharing at github.com/oceansites

### ISSUE THREAD

**Issue by cgallage** [oceansites/dmt#33]
Create a repository for code sharing at github.com/oceansites. (e.g., github.com/ioos and ioos.github.io)

**Comment by hmsnaith** [comment]
Anyone object to me adding a 'software' repo to oceansites as suggested in #7 ? Respond by Wednesday 17 Aug!

**Comment by dpsnowden** [comment]
No objections from me.  I suppose I don't care as much how this happens as long as it does happen in a way that all of the DMT can understand.  @mbarimike  or @hmsnaith, whoever acts first, can you close this issue when you're done?

**Comment by hmsnaith** [comment]
software repo setup next to dmt repo - now just populate it!

**Comment by MBARIMike** [comment]
I moved the utilities folder from the dmt repository to the compliance_report folder in the software repository. The Pull Requests https://github.com/oceansites/dmt/pull/38 and https://github.com/oceansites/software/pull/1 need to be merged for the move to be completed.

**Comment by dpsnowden** [comment]
Closing this.  The basic repo is in place for action tracking and a general code repo also exists.  Thanks @MBARIMike
