### ISSUE TITLE
Can't take assignment of issue, or mark as closed

### ISSUE THREAD

**Issue by hmsnaith** [oceansites/dmt#37]
I'm trying to take the assignment for #33 to be able to mark as closed, but don't seem to be able to.
Am I being dim? or do I need extra permissions somewhere?
I can, clearly, add new issues!

**Comment by dpsnowden** [comment]
I didn't see this until after I already closed #33.  Not sure if there are permissions issues but I assume anyone can assign themselves work.

**Comment by dpsnowden** [comment]
@hmsnaith is this resolved? If so can you close?

**Comment by hmsnaith** [comment]
@dpsnowden I can't assign myself issues. According to the help (https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) I should see a check-box next to the issue, to select then assign the task. I don't get the check-box, so I can't assign the issue to myself

**Comment by dpsnowden** [comment]
@hmsnaith what if you click to the issue page such as this one.  #37 Do you see the  "Assignees" menu to the right of the page?  If so, can you click on it?  That's where I see the pull down menu.  I do not have a checkbox in the larger issue list either.

**Comment by dpsnowden** [comment]
@hmsnaith actually I just discovered that I do have a check box in the issue list.  I suppose there are two ways to assign issues.  I'll look into your permissions.

**Comment by hmsnaith** [comment]
Ok - needs admin / write permission!
