### ISSUE TITLE
Write short document describing organization of the Google Drive folders and document version strategy.

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#4]
@dpsnowden will write a draft and circulate and include a description of how we can use GDrive for notes in addition to version controlled documents.

**Comment by dpsnowden** [comment]
Note, this **_proposal_** does not include a discussion of the root folder structure as discussed in #14 
Please edit this post or add to the thread with new recommendations.  Let's close this quickly as it defines how we will work on a large part of our near term work plan.

Nomenclature:
*  Google Docs format vs MS Word document uploaded to Google Drive:
  * One can publish many file types to google drive which is nothing more than a cloud storage system.  You can upload a microsoft word, excel, or powerpoint file to GDrive.  You can also upload pdfs, images, netcdf files etc.  These files are available for download by anyone with whom they were shared.  For certain file types, Google provides a native equivalent format that provides editing capability.  For documents GDoc format is the analog to MS Word.  An MS Word file uploaded to GDrive cannot be edited.  But a Word file uploaded to GDrive that is converted to GDocs can be edited.  Similarly, documents created initially in google docs format are editable by anyone with whom it was shared.
 *  Best practice is to create all docs in GDocs format and only convert to MS Word if absolutely necessary and after the vast majority of the edits have been completed.

Highest level directory for a document.  Using Data Format Guide as an example throughout.
```
root folder/Data Format Guide/
```

Working Versions
```
root folder/Data Format  Guide/v1.6 Working
```
Published/Finalized Versions
```
root folder/Data Format Guide/Final/my_version_controlled_filename_v1.6.pdf
```

Basics:

1. Each document is assigned an editor.  The editor can rotate through the course of the document.
2. Each document has a version section in the front matter which tracks the major changes resulting in the publication of a new version (e.g. v1.3 to v1.4 of the Data Format guide)
3. A folder is created for each new version (e.g. "Data Format v1.4")
3. All revisions to the version under consideration are done by editing a GDocs version of the document in question (i.e. google docs versions are the native format on Google Drive that allow for all collaborators to edit the document.).
4. A tagging scheme should be devised so that any github issue tagged appropriately will be considered for inclusion in a document update
   1. TODO: Include an example here.  e.g. github.com/oceansites/issues/#14 tagged as `data-format-1.4` or similar.
5. Once the editor decides that a version of the document in question is complete, it is designated read only and a pdf (and possibly word version) are created for publication to the oceansites.org/data web site and to the Final folder on GDrive.  Permissions should be read only for almost everyone except the editor and the project office.
6. DMT Chair does not need to be the editor for all docs.

**Comment by hmsnaith** [comment]
So, if i understand discussion at today's meeting - we add an extra role / step at 7.
'Publisher' or 'approver' - which may need to be DMT chair - to get this 'final version' signed off by OceanSITES EB

**Comment by tcarval** [comment]
This could be closed, the documentation is well organized

**Comment by dpsnowden** [comment]
Agreed, closing.  @tcarval
