### ISSUE TITLE
Ingest new NACLIM products and serve via ERDDAP

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#40]
There are new products from the [NACLIM](http://www.naclim.eu/) project that we should include in the OceanSITES products repository.  Work with Johannes to determine a path forward.

**Comment by tcarval** [comment]
Message from Martin Moritz, NACLIM to Corentin:
_"The data will not be made freely available until the end of the NACLIM project which is in January 2017. I will then submit the (updated) time series to you."_

This action is pending.

**Comment by tcarval** [comment]
The Nacclim data is available here:
ftp://ftp.ifremer.fr/ifremer/oceansites/DATA/NACLIM/

They were delivered in June 2017.
This action may be transfered to Kevin for ERDDAP connectivity.

**Comment by tcarval** [comment]
Nacclim data are available in the DATA directory.
The ERDDAP connection is a separate action.
