### ISSUE TITLE
Update Data Users Guide 

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#5]
Mathias to update the current data users guide and publish.

**Comment by ngalbraith** [comment]
Note: this task is tightly tied to shortening the Data Format Reference Manual. The text for the Data Users' Guide is supposed to be removed from the DFRM - this should NOT be yet more text!

**Comment by dpsnowden** [comment]
From Mantis.  
"add reference to netCDF, ACDD, and CF to manual or user documentation"

I'm assuming this Mantis action is related to the users guide so I did not create a new issue.  @matthiaslankhorst do you agree?

**Comment by dpsnowden** [comment]
Update from @ngalbraith  via email on 10/11/2016
This has been done.The attributes all have a note about where they come
from, or if they're of especial importance to the GDACs (used in software).
Nan

Not closing this issue until we decide if and how to create the Users Guide.

**Comment by dpsnowden** [comment]
Closing based on @ngalbraith email on 10/13.
