### ISSUE TITLE
Collect code examples and populate new Github repo

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#7]
Nathan volunteered to assemble the existing scripts that might be useful to anyone trying to read/write OS files.  After assembling the files we should create a new repo and populate it with the example code.  

I strongly urge us not to use this repo for that purpose.

**Comment by hmsnaith** [comment]
By 'new repo' - would that be parallel to the dmt repo under oceansites?
Maybe oceansites/code_snippets? or something like that, as we aren't putting together a 'package', but a collection

**Comment by MBARIMike** [comment]
How about a general repository name like "software"? I added a "utilities" directory to this repo where I put compliance_report.py software (violating the urging of @dpsnowden) . If we make a software repo I can move it there.

**Comment by hmsnaith** [comment]
New repo called software now setup - @MBARIMike  can you move your utilities into the new repo now?

**Comment by dpsnowden** [comment]
Closing this as it is duplicative of #33 which is also closed.
